/*
*
*           RaphaëlTools : Raphaël extension (button, sliders, ...)         
*                                                                             
*                            version 0.7 (2013-08-20)                         
*  
*                    Copyright (C)  2011 - 2013  Jan Stransky                 
*  
*           Czech Technical University, Faculty of Civil Engineering,         
*       Department of Structural Mechanics, 166 29 Prague, Czech Republic     
*  
*  RaphaëlTools is free software: you can redistribute it and/or modify it
*  under the terms of the GNU Lesser General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or (at your
*  option) any later version.
*  
*  RaphaëlTools is distributed in the hope that it will be useful, but
*  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*  or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
*  License for more details.
*  
*  You should have received a copy of the GNU Lesser General Public License
*  along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
var RaphaelTools={},onDragMove=function(a,b){var c=Raphael.raphaeltoolsDrawingUnit||1;this.onDragUpdate(1/c*(a-(this.deltax||0)),1/c*(b-(this.deltay||0)));this.deltax=a;this.deltay=b},onDragStart=function(){this.deltax=this.deltay=0},onDragStop=function(){this.onDragStop()};Raphael.el.fillRed=function(){return this.attr({fill:"#f00"})};Raphael.el.fillGreen=function(){return this.attr({fill:"#0f0"})};Raphael.el.fillBlue=function(){return this.attr({fill:"#00f"})};Raphael.el.fillYellow=function(){return this.attr({fill:"#ff0"})};
Raphael.el.fillCyan=function(){return this.attr({fill:"#0ff"})};Raphael.el.fillMagenta=function(){return this.attr({fill:"#f0f"})};Raphael.el.fillOrange=function(){return this.attr({fill:"#f50"})};Raphael.el.fillBlack=function(){return this.attr({fill:"#000"})};Raphael.el.fillWhite=function(){return this.attr({fill:"#fff"})};Raphael.el.fillGray=function(){return this.attr({fill:"#777"})};Raphael.el.strokeRed=function(){return this.attr({stroke:"#f00"})};Raphael.el.strokeGreen=function(){return this.attr({stroke:"#0f0"})};
Raphael.el.strokeBlue=function(){return this.attr({stroke:"#00f"})};Raphael.el.strokeYellow=function(){return this.attr({stroke:"#ff0"})};Raphael.el.strokeCyan=function(){return this.attr({stroke:"#0ff"})};Raphael.el.strokeMagenta=function(){return this.attr({stroke:"#f0f"})};Raphael.el.strokeOrange=function(){return this.attr({stroke:"#f50"})};Raphael.el.strokeBlack=function(){return this.attr({stroke:"#000"})};Raphael.el.strokeWhite=function(){return this.attr({stroke:"#fff"})};
Raphael.el.strokeGray=function(){return this.attr({stroke:"#777"})};Raphael.el.red=function(){this.fillRed();return this.strokeRed()};Raphael.el.green=function(){this.fillGreen();return this.strokeGreen()};Raphael.el.blue=function(){this.fillBlue();return this.strokeBlue()};Raphael.el.yellow=function(){this.fillYellow();return this.strokeYellow()};Raphael.el.cyan=function(){this.fillCyan();return this.strokeCyan()};Raphael.el.magenta=function(){this.fillMagenta();return this.strokeMagenta()};
Raphael.el.orange=function(){this.fillOrange();return this.strokeOrange()};Raphael.el.black=function(){this.fillBlack();return this.strokeBlack()};Raphael.el.white=function(){this.fillWhite();return this.strokeWhite()};Raphael.el.gray=function(){this.fillGray();return this.strokeGray()};Raphael.el.stroke=function(a){return this.attr({stroke:a})};Raphael.el.fill=function(a){return this.attr({fill:a})};Raphael.el.setWidth=function(a){return this.attr({"stroke-width":a})};
RaphaelTools.vecTrans=function(a,b,c,d){return[a*d-b*c,a*c+b*d]};RaphaelTools.Point2d=function(a,b){this.x=a||0;this.y=b||0;this.copies=[];this.copiesShifts=[]};RaphaelTools.Point2d.prototype.toString=function(){return"Point2d ( "+this.x+","+this.y+" )"};RaphaelTools.Point2d.prototype.copy=function(a){for(var b=0;b<a.length;b++)this.copiesShifts.push(a[b]),this.copies.push(RaphaelTools.Point2d.create(this.x+a[b][0],this.y+a[b][1]))};
RaphaelTools.Point2d.prototype.setXY=function(a,b){this.x=a;this.y=b;this.update()};RaphaelTools.Point2d.prototype.setX=function(a){this.x=a;this.update()};RaphaelTools.Point2d.prototype.setY=function(a){this.y=a;this.update()};RaphaelTools.Point2d.prototype.translate=function(a,b){this.x+=a;this.y+=b;this.update()};RaphaelTools.Point2d.prototype.translateX=function(a){this.translate(a,0)};RaphaelTools.Point2d.prototype.translateY=function(a){this.translate(0,a)};
RaphaelTools.Point2d.prototype.update=function(){for(var a=0;a<this.copies.length;a++)this.copies[a].setXY(this.x+this.copiesShifts[a][0],this.y+this.copiesShifts[a][1]),this.copies[a].update()};RaphaelTools.Point2d.create=function(a,b){var c=new RaphaelTools.Point2d(a,b);c.update();return c};
RaphaelTools.Point3d=function(a,b,c,d){this.xr=a||0;this.yr=b||0;this.zr=c||0;this.copies=[];this.copiesShifts=[];this.p=void 0==d?[[1,0,0],[0,1,0],[0,0,1]]:d;this.x=this.p[0][0]*this.xr+this.p[0][1]*this.yr+this.p[0][2]*this.zr+(this.p[0][3]||0);this.y=this.p[1][0]*this.xr+this.p[1][1]*this.yr+this.p[1][2]*this.zr+(this.p[1][3]||0);this.z=this.p[2][0]*this.xr+this.p[2][1]*this.yr+this.p[2][2]*this.zr+(this.p[2][3]||0)};
RaphaelTools.Point3d.prototype.toString=function(){return"Point3d ( "+this.xr+","+this.yr+","+this.zr+" )"};RaphaelTools.Point3d.prototype.copy=function(a){for(var b=0;b<a.length;b++)this.copiesShifts.push(a[b]),this.copies.push(new RaphaelTools.Point3d(this.xr+a[b][0],this.yr+a[b][1],this.zr+a[b][2]))};RaphaelTools.Point3d.prototype.setXYZ=function(a,b,c){this.xr=a;this.yr=b;this.zr=c;this.update()};RaphaelTools.Point3d.prototype.setX=function(a){this.xr=a;this.update()};
RaphaelTools.Point3d.prototype.setY=function(a){this.yr=a;this.update()};RaphaelTools.Point3d.prototype.setZ=function(a){this.zr=a;this.update()};RaphaelTools.Point3d.prototype.translate=function(a,b,c){this.xr+=a;this.zr+=c;this.yr+=b;this.update()};RaphaelTools.Point3d.prototype.translateX=function(a){this.translate(a,0,0)};RaphaelTools.Point3d.prototype.translateY=function(a){this.translate(0,a,0)};RaphaelTools.Point3d.prototype.translateZ=function(a){this.translate(0,0,a)};
RaphaelTools.Point3d.prototype.setProjection=function(a){this.p=a;this.update()};RaphaelTools.Point3d.prototype.project=function(){this.x=this.p[0][0]*this.xr+this.p[0][1]*this.yr+this.p[0][2]*this.zr+(this.p[0][3]||0);this.y=this.p[1][0]*this.xr+this.p[1][1]*this.yr+this.p[1][2]*this.zr+(this.p[1][3]||0);this.z=this.p[2][0]*this.xr+this.p[2][1]*this.yr+this.p[2][2]*this.zr+(this.p[2][3]||0)};
RaphaelTools.Point3d.prototype.rotX=function(a){var b=Math.cos(a);a=Math.sin(a);var c=this.p,d=c[1][0],f=c[1][1],e=c[1][2],g=c[2][0],h=c[2][1],l=c[2][2];c[1][0]=d*b-g*a;c[2][0]=d*a+g*b;c[1][1]=f*b-h*a;c[2][1]=f*a+h*b;c[1][2]=e*b-l*a;c[2][2]=e*a+l*b;this.update()};
RaphaelTools.Point3d.prototype.rotY=function(a){var b=Math.cos(a);a=Math.sin(a);var c=this.p,d=c[0][0],f=c[0][1],e=c[0][2],g=c[2][0],h=c[2][1],l=c[2][2];c[0][0]=d*b-g*a;c[2][0]=d*a+g*b;c[0][1]=f*b-h*a;c[2][1]=f*a+h*b;c[0][2]=e*b-l*a;c[2][2]=e*a+l*b;this.update()};
RaphaelTools.Point3d.prototype.rotZ=function(a){var b=Math.cos(a);a=Math.sin(a);var c=this.p,d=c[0][0],f=c[0][1],e=c[0][2],g=c[1][0],h=c[1][1],l=c[1][2];c[0][0]=d*b-g*a;c[1][0]=d*a+g*b;c[0][1]=f*b-h*a;c[1][1]=f*a+h*b;c[0][2]=e*b-l*a;c[1][2]=e*a+l*b;this.update()};RaphaelTools.Point3d.prototype.update=function(){this.project();for(var a=0;a<this.copies.length;a++)this.copies[a].setXYZ(this.xr+this.copiesShifts[a][0],this.yr+this.copiesShifts[a][1],this.zr+this.copiesShifts[a][2]),this.copies[a].update()};
RaphaelTools.Point3d.create=function(a,b,c,d){a=new RaphaelTools.Point3d(a,b,c,d);a.update();return a};
Raphael.fn.LineSegment=function(a,b,c){c=void 0==c?{}:c;c=this.path().attr(c);c.point1=a;c.point2=b;c.copies=[];c.copiesPoints=[[],[]];c.update=function(){this.attr({path:[["M",this.point1.x,this.point1.y],["L",this.point2.x,this.point2.y]]});for(var a=0;a<this.copies.length;a++)this.copies[a].update()};c.copy=function(a){for(var b=0;b<a[0].length;b++)this.copiesPoints[0].push(a[0][b]),this.copiesPoints[1].push(a[1][b]),this.copies.push(this.makeCopy(a[0][b],a[1][b]));this.update()};c.makeCopy=function(a,
b){var c=this.paper.LineSegment(a,b);c.attr(this.attr());c.update();return c};c.update();return c};
Raphael.fn.LineBR=function(a,b,c,d,f,e){e=void 0==e?{}:e;e=this.path().attr(e);e.a=void 0==a?1:a;e.b=void 0==b?1:b;e.c=void 0==c?1:c;e.lt=d||RaphaelTools.Point2d.create();e.rb=f||RaphaelTools.Point2d.create();e.point1=RaphaelTools.Point2d.create();e.point2=RaphaelTools.Point2d.create();e.isOutsideBR=!0;e.setABC=function(a,b,d){this.a=a;this.b=b;this.c=d;this.update()};e.setA=function(a){this.a=a;this.update()};e.setB=function(a){this.b=a;this.update()};e.setC=function(a){this.c=a;this.update()};e.findSections=
function(){var a,b,d=this.a,c=this.b,e=this.c,f=this.point1,n=this.point2,m=this.lt;a=this.rb;var j=m.y,k=a.y,m=m.x,p=a.x;this.show();this.isOutsideBR=!1;0==d?-e/c>j&&-e/c<k?(f.setXY(m,-e/c),n.setXY(p,-e/c)):(this.hide(),this.isOutsideBR=!0):0==c?-e/d>m&&-e/d<p?(f.setXY(-e/d,j),n.setXY(-e/d,k)):(this.hide(),this.isOutsideBR=!0):(a=-(d*m+e)/c,b=-(d*p+e)/c,a<j&&b<j?(this.hide(),this.isOutsideBR=!0):a>k&&b>k?(this.hide(),this.isOutsideBR=!0):a>j&&a<k&&b>j&&b<k?(f.setXY(m,a),n.setXY(p,b)):a<j&&b>k||a>
k&&b<j?(f.setXY(-(c*j+e)/d,j),n.setXY(-(c*k+e)/d,k)):a<k&&a>j?(f.setXY(m,a),b<j?n.setXY(-(c*j+e)/d,j):n.setXY(-(c*k+e)/d,k)):(n.setXY(p,b),a<j?f.setXY(-(c*j+e)/d,j):f.setXY(-(c*k+e)/d,k)))};e.normalize=function(){if(1!=this.a*this.a+this.b*this.b){var a=Math.sqrt(this.a*this.a+this.b*this.b);this.a/=a;this.b/=a;this.c/=a}};e.update=function(){this.normalize();this.findSections();this.attr({path:[["M",this.point1.x,this.point1.y],["L",this.point2.x,this.point2.y]]})};e.update();return e};
Raphael.fn.Path=function(a,b){b=void 0==b?{}:b;var c=this.path(a).attr(b);c.pathList=a;c.setItem=function(a,b,c){this.pathList[a][b]=c;this.update()};c.iaddItem=function(a,b,c){this.pathList[a][b]+=c;this.update()};c.setNewPath=function(a){this.pathList=a;this.update()};c.update=function(){this.attr({path:this.pathList})};c.update();return c};
Raphael.fn.Circle=function(a,b,c,d){d=void 0==d?{}:d;d=this.circle(a,b,c).attr(d);d.x=a;d.y=b;d.r=c;d.copies=[];d.copiesShifts=[];d.setR=function(a){this.r=a;this.update()};d.setXYR=function(a,b,c){this.x=a;this.y=b;this.r=c;this.update()};d.setXY=function(a,b){this.x=a;this.y=b;this.update()};d.setX=function(a){this.x=a;this.update()};d.setY=function(a){this.y=a;this.update()};d.translate=function(a,b){this.x+=a;this.y+=b;this.update()};d.translateX=function(a){this.translate(a,0)};d.translateY=
function(a){this.translate(0,a)};d.copy=function(a){for(var b=0;b<a.length;b++)this.copiesShifts.push(a[b]),this.copies.push(this.makeCopy());this.update()};d.makeCopy=function(){var a=this.paper.Circle(0,0,0);a.attr(this.attr());a.update();return a};d.update=function(){this.attr({cx:this.x,cy:this.y,r:this.r});for(var a=0;a<this.copies.length;a++)this.copies[a].setXYR(this.x+this.copiesShifts[a][0],this.y+this.copiesShifts[a][1],this.r)};d.update();return d};
Raphael.fn.SliderCirc=function(a){a=void 0==a?{}:a;var b=this.circle(0,0).attr({fill:"#f00",r:6,"stroke-width":2,cursor:"move"});b.attr(a);b.getX=function(){return this.attr("cx")};b.setX=function(a){this.attr({cx:a})};b.getY=function(){return this.attr("cy")};b.setY=function(a){this.attr({cy:a})};return b};
Raphael.fn.SliderRect=function(a){a=void 0==a?{}:a;a=this.rect(0,0,13,13,3).attr({fill:"#f00",cursor:"move"}).attr(a);a.getX=function(){return this.attr("x")+0.5*this.attr("width")};a.setX=function(a){this.attr({x:a-0.5*this.attr("width")})};a.getY=function(){return this.attr("y")+0.5*this.attr("height")};a.setY=function(a){this.attr({y:a-0.5*this.attr("height")})};return a};
Raphael.fn.Slider=function(a,b){var c=this.path(),d=a?a:this.SliderRect();d.onmove=function(){};d.getVal=function(){var a=this.getX(),b=this.getY(),a=Math.sqrt((a-this.x)*(a-this.x)+(b-this.y)*(b-this.y))-this.start;return this.val1+a*(this.val2-this.val1)/this.lenVals};d.setVal=function(a){a<Math.min(this.val3,this.val4)&&(a=Math.min(this.val3,this.val4));a=this.start+this.lenVals/(this.val2-this.val1)*(a-this.val1);a<this.start?(this.maxFlag=!1,this.minFlag=!0,a=this.start):a>this.stop?(this.maxFlag=
!0,this.minFlag=!1,a=this.stop):this.maxFlag=this.minFlag=!1;this.setX(this.x+a*this.cos);this.setY(this.y+a*this.sin);this.onDragStop()};b=b||{};d.x=void 0==b.x?100:b.x;d.y=void 0==b.y?100:b.y;d.dx=void 0==b.dx?100:b.dx;d.dy=void 0==b.dy?0:b.dy;d.len=Math.sqrt(d.dx*d.dx+d.dy*d.dy);d.cos=d.dx/d.len;d.sin=d.dy/d.len;var f=void 0==b.lineAttrs?{}:b.lineAttrs;d.gap=void 0==b.gap?12:b.gap;d.start=d.gap;d.stop=d.len-d.start;d.val1=void 0==b.val1?0:b.val1;d.val2=void 0==b.val2?1:b.val2;d.val3=void 0==b.val3?
d.val1:b.val3;d.val4=void 0==b.val4?d.val2:b.val4;var e=void 0==b.initVal?0.5*(d.val1+d.val2):b.initVal;d.lenVals=d.len-2*d.start;d.left=d.start+(d.val3-d.val1)/(d.val2-d.val1)*d.lenVals;d.right=d.start+(d.val4-d.val1)/(d.val2-d.val1)*d.lenVals;d.line=c.attr({path:[["M",d.x,d.y],["l",d.dx,d.dy]],stroke:"#000","stroke-width":7}).attr(f);d.attr({cursor:"move"});d.onDragStop=function(){this.posX=this.getX();this.posY=this.getY()};d.onDragStop();d.setVal(e);d.minFlag=!1;d.maxFlag=!1;d.onDragUpdate=function(a,
b){this.posX+=a;this.posY+=b;var c=(this.posX-this.x)*this.cos+(this.posY-this.y)*this.sin;c<this.left?(this.minFlag||(this.setX(this.x+this.left*this.cos),this.setY(this.y+this.left*this.sin),this.onmove()),this.minFlag=!0,this.maxFlag=!1):c>this.right?(this.maxFlag||(this.setX(this.x+this.right*this.cos),this.setY(this.y+this.right*this.sin),this.onmove()),this.minFlag=!1,this.maxFlag=!0):(this.setX(this.x+c*this.cos),this.setY(this.y+c*this.sin),this.maxFlag=this.minFlag=!1,this.onmove())};d.drag(onDragMove,
onDragStart,onDragStop);return d};
Raphael.fn.TextBox=function(a){a=a||{};var b=void 0==a.x?100:a.x,c=void 0==a.y?100:a.y,d=void 0==a.width?100:a.width,f=void 0==a.height?100:a.height,e=void 0==a.str?"string":a.str,g=void 0==a.rectAttrs?{}:a.rectAttrs;a=void 0==a.textAttrs?{}:a.textAttrs;g=this.rect(b,c,d,f).attr(g);g.text=this.text(b+0.5*d,c+0.5*f,e).attr({"font-size":20}).attr(a);g.x=b;g.y=c;g.width=d;g.height=f;g.str=e;g.update=function(){this.attr({x:this.x,y:this.y});this.text.attr({x:this.x+0.5*this.width,y:this.y+0.5*this.height,
text:this.str})};g.setXY=function(a,b){this.x=a;this.y=b;this.update()};g.setX=function(a){this.x=a;this.update()};g.setY=function(a){this.y=a;this.update()};g.setStr=function(a){this.str=a;this.update()};return g};
Raphael.fn.Button=function(a){void 0==a.x&&(a.x=100);void 0==a.y&&(a.y=100);void 0==a.width&&(a.width=100);void 0==a.height&&(a.height=30);void 0==a.r&&(a.r=4);void 0==a.bgColor&&(a.bgColor="#bbb");void 0==a.bgColorWhenClicked&&(a.bgColorWhenClicked="#aaa");var b=this.TextBox(a),c=void 0==a.r?4:a.r;b.cover=this.rect(b.x,b.y,b.width,b.height).attr({fill:"#000",opacity:0,cursor:"pointer"});b.cover.button=b;b.bgColor=void 0==a.bgColor?"#bbb":a.bgColor;b.bgColorWhenClicked=void 0==a.bgColorWhenClicked?
"#aaa":a.bgColorWhenClicked;b.attr({r:c,fill:b.bgColor});b.onClick=function(){};b.doThisWhenClicked=function(){this.text.attr({x:this.x+0.5*this.width+2});this.attr({fill:this.bgColorWhenClicked});this.onClick()};b.doThisWhenUnclicked=function(){this.text.attr({x:this.x+0.5*this.width});this.attr({fill:this.bgColor})};b.cover.mousedown(function(){this.button.doThisWhenClicked()});b.cover.mouseup(function(){this.button.doThisWhenUnclicked()});b.cover.mouseout(function(){this.button.doThisWhenUnclicked()});
return b};
RaphaelTools.Legend=function(a,b,c){this.x=void 0==c.x?0:c.x;this.y=void 0==c.y?0:c.y;this.len=void 0==c.len?100:c.len;this.fontSize=void 0==c.fontSize?15:c.fontSize;this.dy=void 0==c.dy?30:c.dy;for(var d,f,e,g=this.y,h=0;h<b.length;h++)c=b[h][0],d=1<b[h].length?b[h][1]:"#000",f=2<b[h].length?b[h][2]:1,e=3<b[h].length?b[h][3]:{},e["stroke-width"]=f,e.stroke=d,a.path([["M",this.x,g],["l",this.len,0]]).attr(e),a.text(this.x+this.len+20,g,c).attr({"font-size":this.fontSize,"text-anchor":"start"}),g+=
this.dy};RaphaelTools.Legend.create=function(a,b,c){return new RaphaelTools.Legend(a,b,c)};
Raphael.fn.CheckBox=function(a){a=void 0==a?{}:a;var b=void 0==a.x?100:a.x,c=void 0==a.y?100:a.y,d=void 0==a.dim?20:a.dim,f=void 0==a.isChecked?!1:a.isChecked,e=void 0==a.rectAttrs?{}:a.rectAttrs;a=void 0==a.pathAttrs?{}:a.pathAttrs;e=this.rect(b,c,d,d).attr({"stroke-width":2,fill:"#fff"}).attr(e);e.x=b;e.y=c;e.dim=d;e.isChecked=f;e.path=this.path([["M",e.x+0.2*e.dim,e.y+0.4*e.dim],["l",0.2*e.dim,0.3*e.dim],["l",0.4*e.dim,-0.5*e.dim]]).attr({"stroke-width":3}).attr(a);e.isChecked||e.path.hide();e.cover=
this.rect(b,c,d,d).attr({fill:"#000",opacity:0,cursor:"pointer"});e.cover.checkBox=e;e.cover.click(function(){this.checkBox.check(!this.checkBox.isChecked);this.checkBox.onChange()});e.onChange=function(){};e.check=function(a){void 0==a||a?(this.path.show(),this.isChecked=!0):(this.path.hide(),this.isChecked=!1)};e.uncheck=function(){this.check(!1)};return e};
